language: node_js
node_js:
  - "6"
deploy:
  provider: npm
  email: $EMAIL_TOKEN
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    branch: master
    repo: echoes221/scroll-progress-react
notifications:
  email: false
